import { planFor } from './content-quality.mjs'

const cut = (part, quantity, thickness, width, length, notes) => ({ part, quantity, thickness, width, length, ...(notes ? { notes } : {}) })

const commonFinish = 'Sand a labeled offcut through 180 grit, apply the complete finish schedule, and allow the stated full cure before use'
const plywoodJoinery = 'dados or rabbets with glue and screws, plus a back or brace that locks the assembly square'

const rules = [
  { test: /end-grain cutting board/i, plan: { size: '18 × 12 × 1-1/2 in after flattening', metric: '457 × 305 × 38 mm after flattening', stock: 'clear dry 8/4 closed-grain hardwood, all pieces from sound stock with no checks, bark, or open defects', joinery: 'two-stage long-grain lamination: make and flatten the first panel, crosscut equal rows, rotate end grain upward, then glue the rows on a verified flat reference', finish: 'use a fully cured finish whose manufacturer supports the intended cutting-board contact; wash by hand and dry upright', cutList: [cut('First-lamination strips', 12, '1-3/4 in', '1-1/2 in', '13 in', 'Joint matching faces and keep grain orientation deliberate'), cut('End-grain rows after first glue-up', 7, '1-1/2 in', '1-3/4 in', '18 in', 'Crosscut from the flattened first panel, rotate end grain up, and keep the sequence labeled'), cut('Glue-up test pair', 2, 'Match stock', '2 in', '4 in'), cut('Finish sample', 1, 'Match stock', '2 in', '4 in')] } },
  { test: /cutting board with safe grain orientation/i, plan: { size: '18 × 10 × 3/4 in after flattening', metric: '457 × 254 × 19 mm after flattening', stock: 'clear dry closed-grain hardwood strips with sound long-grain glue faces and no open defects', joinery: 'edge-grain strip lamination on a verified flat reference with the growth-ring and color layout chosen before glue', finish: 'use a fully cured finish whose manufacturer supports the intended cutting-board contact; wash by hand and dry upright', cutList: [cut('Center strips', 4, '1 in rough', '2 in', '20 in'), cut('Edge strips', 2, '1 in rough', '1 in', '20 in'), cut('Glue-up setup pieces', 2, 'Match stock', '2 in', '6 in'), cut('Finish sample', 1, 'Match stock', '2 in', '4 in')] } },
  { test: /outdoor dining table/i, plan: { size: '72 × 36 × 30 in high baseline', metric: '1829 × 914 × 762 mm high', stock: 'straight naturally durable or correctly treated exterior lumber with corrosion-resistant hardware compatible with the stock', joinery: 'braced mortise-and-tenon or approved mechanical base with individually fastened top slats, drainage gaps, and movement allowance', finish: 'exterior finish proven on the same stock; seal vulnerable end grain and preserve drainage and inspection access', cutList: [cut('Top slats', 9, '3/4–1 in', '3-3/4 in', '74 in', 'Space evenly for drainage after the stock reaches service moisture'), cut('Legs', 4, '2-1/2 in', '2-1/2 in', '29 in'), cut('Long aprons', 2, '1 in', '4 in', '65 in'), cut('End aprons', 2, '1 in', '4 in', '29 in'), cut('Top support rails', 3, '1 in', '3 in', '29 in'), cut('Finish and fastener samples', 2, 'Match project', '4 in', '12 in')] } },
  { test: /birdhouse with species-appropriate dimensions/i, plan: { size: 'Eastern-bluebird example: 5 × 5 in floor, 1-1/2 in entrance, 6 in from floor; replace with a current plan for the selected local species', metric: 'Eastern-bluebird example: 127 × 127 mm floor, 38 mm entrance, 152 mm from floor; replace with current local-species guidance', stock: 'untreated 3/4 in cedar or pine with a rough interior below the entrance', joinery: 'exterior screws, drainage corners, high ventilation, sloped roof, and a hinged or removable cleanout side; no perch', finish: 'leave the interior and entrance unfinished; finish the exterior only when current species guidance permits it', cutList: [cut('Floor', 1, '3/4 in', '5 in', '5 in', 'Clip corners for drainage'), cut('Front', 1, '3/4 in', '5 in', '8 in', 'Drill entrance from the selected current species plan'), cut('Back', 1, '3/4 in', '5 in', '12 in', 'Extend for mounting when appropriate'), cut('Sides', 2, '3/4 in', '5 in', '6-1/2–8 in', 'Slope tops for roof and provide cleanout access'), cut('Roof', 1, '3/4 in', '7 in', '8 in')] } },
  { test: /bat house using conservation guidelines/i, plan: { size: '36 × 24 × about 4 in; chamber spacing and mounting from current regional conservation guidance', metric: '914 × 610 × about 102 mm; chamber spacing and mounting from current regional conservation guidance', stock: 'untreated exterior plywood and cedar trim with roughened interior surfaces and no plastic mesh', joinery: 'sealed multi-chamber roost with roughly 3/4 in chamber spacing, extended landing area, rain-shedding roof, and mounting into verified structure', finish: 'leave roost surfaces untreated; select exterior color and solar exposure from current regional climate guidance', cutList: [cut('Back', 1, '3/4 in', '24 in', '36 in'), cut('Front panels', 2, '1/2 in', '24 in', '28–32 in'), cut('Chamber spacers', 8, '3/4 in', '3/4 in', '32 in'), cut('Interior baffles', 2, '1/4–1/2 in', '22-1/2 in', '30 in', 'Roughen or kerf gripping surfaces without trapping mesh'), cut('Roof', 1, '3/4 in', '6 in', '26 in')] } },
  { test: /wall shelf with hidden brackets|floating (?:bathroom )?shelf|floating shelves/i, plan: { size: '36 × 9 × 2-1/4 in shelf body', metric: '914 × 229 × 57 mm shelf body', stock: '3/4 in hardwood or cabinet plywood skins over a straight internal frame', joinery: 'hollow torsion-box shelf over a rated concealed bracket or verified wall cleat', finish: commonFinish, cutList: [cut('Top and bottom skins', 2, '1/4–3/4 in', '9 in', '36 in'), cut('Front edge', 1, '3/4 in', '2-1/4 in', '36 in'), cut('Internal ribs', 5, '3/4 in', '1-1/2 in', '7-1/2 in'), cut('Wall cleat or bracket', 1, 'Per rating', 'Fit cavity', '34 in', 'Connect to verified framing or masonry')] } },
  { test: /full-size furniture layout rod/i, plan: { size: '48 × 2 × 1/4 in story rod', metric: '1219 × 51 × 6 mm story rod', stock: 'straight stable plywood or clear hardwood strip', joinery: 'one-piece story rod with labeled faces; no assembly required', finish: 'leave unfinished or seal lightly without obscuring pencil and knife marks', cutList: [cut('Story rod', 1, '1/4 in', '2 in', '48 in'), cut('Short vertical rod', 1, '1/4 in', '2 in', '36 in'), cut('Practice strip', 1, '1/4 in', '2 in', '12 in')] } },
  { test: /marking gauge from scrap/i, plan: { size: '8 in beam with 2-1/2 × 2 × 1 in fence', metric: '203 mm beam with 64 × 51 × 25 mm fence', stock: 'straight hardwood scrap and one hardened marking pin or wheel', joinery: 'snug beam mortise with wedge or threaded lock', finish: 'wax the beam lightly; keep the pin and locking faces free of finish', cutList: [cut('Beam', 1, '3/8 in', '3/8 in', '8 in'), cut('Fence', 1, '1 in', '2 in', '2-1/2 in'), cut('Wedge', 1, '1/4 in', '3/4 in', '2 in'), cut('Test beam', 1, '3/8 in', '3/8 in', '4 in')] } },
  { test: /winding sticks/i, plan: { size: '24 × 2-1/2 × 3/4 in each', metric: '610 × 64 × 19 mm each', stock: 'two straight, stable hardwood strips from the same board', joinery: 'matched one-piece sticks with contrasting sighting strip', finish: 'leave the bottom edges unfinished and dead straight; use a low-sheen finish elsewhere', cutList: [cut('Winding sticks', 2, '3/4 in', '2-1/2 in', '24 in'), cut('Contrasting sight strips', 2, '1/8 in', '1/2 in', '24 in'), cut('Reference-edge test strip', 1, '3/4 in', '2 in', '12 in')] } },
  { test: /bench hook/i, plan: { size: '12 × 9 in base', metric: '305 × 229 mm base', stock: '1/2 or 3/4 in plywood base with straight hardwood stops', joinery: 'opposed glued and screwed stops kept clear of the saw path', finish: 'leave work-contact faces unfinished; wax only the bench-contact face if needed', cutList: [cut('Base', 1, '1/2–3/4 in', '9 in', '12 in'), cut('Top fence', 1, '3/4 in', '1-1/2 in', '8 in'), cut('Bench hook', 1, '3/4 in', '1-1/2 in', '8 in')] } },
  { test: /shooting board/i, plan: { size: '20 × 12 in base', metric: '508 × 305 mm base', stock: 'stable plywood base, straight hardwood fence, and replaceable runway', joinery: 'square fence fixed from a verified test cut', finish: 'wax the plane runway only; leave the work reference clean and flat', cutList: [cut('Base', 1, '3/4 in', '12 in', '20 in'), cut('Upper deck', 1, '1/2 in', '8 in', '20 in'), cut('Fence', 1, '1-1/2 in', '2 in', '10 in'), cut('Donkey ear', 1, '3/4 in', '6 in', '10 in', 'Optional for miters')] } },
  { test: /wooden mallet from firewood|hardwood mallet/i, plan: { size: '3 × 5 × 11 in overall', metric: '76 × 127 × 279 mm overall', stock: 'sound, dry hardwood with straight grain through the handle', joinery: 'tapered through-mortise and wedged handle or sound one-piece turning blank', finish: 'light oil or wax after full sanding; no thick slippery film on the handle', cutList: [cut('Head blank', 1, '3 in', '3 in', '5 in'), cut('Handle', 1, '1-1/4 in', '1-1/2 in', '11 in'), cut('Wedges', 2, '1/8 in', '1 in', '2 in')] } },
  { test: /hand-tool tote/i, plan: { size: '24 × 10 × 12 in high', metric: '610 × 254 × 305 mm high', stock: '1/2 in straight pine or hardwood sides with 3/4 in handle stock', joinery: 'dovetailed or rabbeted case with captured bottom and through handle', finish: commonFinish, cutList: [cut('Long sides', 2, '1/2 in', '8 in', '24 in'), cut('End panels', 2, '1/2 in', '12 in', '9 in'), cut('Bottom', 1, '1/2 in', '9 in', '23 in'), cut('Handle', 1, '1 in', '1-1/2 in', '24 in'), cut('Dividers', 2, '1/2 in', '4 in', '9 in')] } },
  { test: /loose-tenon.*router jig|dowel-joint alignment jig|hinge-mortising router template/i, plan: { size: '12 × 6 in reference body; fit to actual joint or hinge', metric: '305 × 152 mm reference body; fit to actual joint or hinge', stock: '1/2 in stable plywood or phenolic-faced sheet with hardwood fences', joinery: 'adjustable square fence with replaceable guide bushing or drill guide', finish: 'wax reference faces only after fit and clamping are verified', cutList: [cut('Guide plate', 1, '1/2 in', '6 in', '12 in'), cut('Reference fence', 1, '3/4 in', '2 in', '12 in'), cut('Adjustable stops', 2, '3/4 in', '1-1/2 in', '4 in'), cut('Replaceable guide insert', 2, '1/4 in', '3 in', '4 in', 'Size opening to actual bit, bushing, or dowel guide')] } },
  { test: /crosscut sled/i, plan: { size: '24 × 30 in base; resize to the actual saw table', metric: '610 × 762 mm base; resize to the actual saw table', stock: '1/2 or 3/4 in flat plywood with straight laminated fences and stable runners', joinery: 'two fitted runners and a rear fence squared by a five-cut test', finish: 'wax runners and underside lightly; keep fence faces clean', cutList: [cut('Base', 1, '1/2–3/4 in', '24 in', '30 in'), cut('Rear fence laminations', 2, '3/4 in', '4 in', '30 in'), cut('Front bridge', 1, '3/4 in', '3 in', '24 in'), cut('Runners', 2, 'Fit slot', 'Fit slot', '24 in'), cut('Blade-exit guard box', 1, '3/4 in', '4 in', '6 in')] } },
  { test: /tapering jig/i, plan: { size: '36 × 8 in base', metric: '914 × 203 mm base', stock: '3/4 in stable plywood with hardwood stops and rated hold-downs', joinery: 'hinged or sliding fence with positive stops outside the blade path', finish: 'wax the machine-contact face only', cutList: [cut('Base', 1, '3/4 in', '8 in', '36 in'), cut('Adjustable fence', 1, '3/4 in', '3 in', '34 in'), cut('Pivot block', 1, '3/4 in', '3 in', '5 in'), cut('Positive stops', 3, '3/4 in', '1-1/2 in', '3 in')] } },
  { test: /box-joint jig/i, plan: { size: '18 × 6 in fence body', metric: '457 × 152 mm fence body', stock: '3/4 in plywood or MDF fence with a replaceable hardwood indexing key', joinery: 'replaceable auxiliary fence indexed to the actual cutter width', finish: 'leave reference faces unfinished and free of glue buildup', cutList: [cut('Auxiliary fence', 1, '3/4 in', '6 in', '18 in'), cut('Index keys', 3, 'Fit cutter', 'Fit cutter', '2 in'), cut('Setup blanks', 4, 'Match project', '3 in', '8 in')] } },
  { test: /thin-rip jig/i, plan: { size: '10 × 3 in body', metric: '254 × 76 mm body', stock: 'stable hardwood or plywood with a smooth bearing', joinery: 'adjustable stop that references the miter slot, never the trapped offcut', finish: 'wax the slot runner lightly; keep bearing secure', cutList: [cut('Body', 1, '3/4 in', '3 in', '10 in'), cut('Slot runner', 1, 'Fit slot', 'Fit slot', '8 in'), cut('Adjustable arm', 1, '1/2 in', '1-1/2 in', '6 in'), cut('Bearing block', 1, '3/4 in', '1-1/2 in', '2 in')] } },
  { test: /table saw jointing jig|straightedge jig for routers and circular saws|zero-clearance circular saw guide/i, plan: { size: '48 × 10 in guide; extend for ordinary stock', metric: '1219 × 254 mm guide; extend for ordinary stock', stock: 'straight 1/2 or 3/4 in plywood base with a factory-edge guide strip', joinery: 'glued and screwed straightedge calibrated to the actual tool offset', finish: 'seal lightly and keep the guide edge unbroken', cutList: [cut('Base', 1, '1/2 in', '10 in', '48 in'), cut('Guide strip', 1, '1/2 in', '4 in', '48 in'), cut('Hold-down blocks', 2, '3/4 in', '2 in', '4 in')] } },
  { test: /bandsaw circle-cutting jig/i, plan: { size: '24 × 12 in base', metric: '610 × 305 mm base', stock: '1/2 in flat plywood with fitted runner and movable pivot', joinery: 'runner registered to blade with a captured adjustable pivot', finish: 'wax runner only after the jig tracks without play', cutList: [cut('Base', 1, '1/2 in', '12 in', '24 in'), cut('Runner', 1, 'Fit slot', 'Fit slot', '18 in'), cut('Pivot bar', 1, '1/2 in', '1-1/2 in', '18 in'), cut('Pivot pins', 3, 'Per hole', 'Per hole', '1 in')] } },
  { test: /bandsaw sled/i, plan: { size: '18 × 12 in carrier', metric: '457 × 305 mm carrier', stock: '1/2 in plywood carrier with hardwood runner and hold-down blocks', joinery: 'fitted runner, square rear fence, and captured workholding', finish: 'wax runner only; keep work-contact faces high-friction', cutList: [cut('Carrier', 1, '1/2 in', '12 in', '18 in'), cut('Rear fence', 1, '3/4 in', '3 in', '12 in'), cut('Runner', 1, 'Fit slot', 'Fit slot', '16 in'), cut('Hold-down blocks', 3, '3/4 in', '2 in', '4 in')] } },
  { test: /zero-clearance inserts/i, plan: { size: 'trace the factory throat plate exactly', metric: 'trace the factory throat plate exactly', stock: 'stable phenolic, hardwood, or plywood matching the factory-plate thickness', joinery: 'snug removable insert with leveling screws and positive retention', finish: 'leave unfinished; wax only where removal requires it', cutList: [cut('Insert blanks', 3, 'Match factory plate', 'Trace plate', 'Trace plate'), cut('Leveling pads', 4, '1/4 in', '1/2 in', '1/2 in'), cut('Setup blank', 1, 'Match factory plate', 'Trace plate', 'Trace plate')] } },
  { test: /outfeed table/i, plan: { size: '48 × 36 in top; height 1/16–1/8 in below saw table', metric: '1219 × 914 mm top; 2–3 mm below saw table', stock: '3/4 in plywood top with torsion-box ribs or straight frame stock', joinery: 'rigid base or rated folding brackets with a flat top and unobstructed miter-slot paths', finish: 'durable low-friction top; no finish that transfers to project stock', cutList: [cut('Top skins', 2, '1/2 in', '36 in', '48 in'), cut('Long ribs', 4, '3/4 in', '3 in', '46-1/2 in'), cut('Cross ribs', 5, '3/4 in', '3 in', '34-1/2 in'), cut('Legs or wall brackets', 2, 'Rated/fit', 'Rated/fit', 'Set to saw height')] } },
  { test: /miter saw station/i, plan: { size: '96 × 24 in bench; deck height set to actual saw', metric: '2438 × 610 mm bench; deck height set to actual saw', stock: '3/4 in plywood cases with straight fence wings and a supported machine deck', joinery: plywoodJoinery, finish: 'durable clear finish; preserve flat fence and deck references', cutList: [cut('Base cabinet sides', 4, '3/4 in', '24 in', '34 in'), cut('Wing tops', 2, '3/4 in', '24 in', '36 in'), cut('Saw deck', 1, '3/4 in', '24 in', '24 in'), cut('Fence wings', 2, '3/4 in', '4 in', '36 in'), cut('Backs', 2, '1/2 in', '36 in', '34 in')] } },
  { test: /miter saw dust hood/i, plan: { size: '36 × 30 × 30 in starting hood; verify full saw travel', metric: '914 × 762 × 762 mm starting hood', stock: '1/2 in plywood panels with flexible side curtains and grounded dust hose where required', joinery: 'screwed hood with removable panels and no obstruction to guards or travel', finish: 'seal interior seams smoothly without restricting motor cooling', cutList: [cut('Back', 1, '1/2 in', '30 in', '36 in'), cut('Top', 1, '1/2 in', '30 in', '36 in'), cut('Side wings', 2, '1/2 in', '24 in', '30 in'), cut('Removable baffle', 1, '1/4 in', '12 in', '30 in')] } },
  { test: /router table into a workbench wing/i, plan: { size: '24 × 32 in top; opening from actual insert plate', metric: '610 × 813 mm top', stock: 'two layers of 3/4 in MDF or plywood with durable laminate faces', joinery: 'laminated top with leveled insert plate and independent fence attachment', finish: 'plastic laminate or hard low-friction finish on both faces', cutList: [cut('Top layers', 2, '3/4 in', '24 in', '32 in'), cut('Insert recess test panel', 1, '3/4 in', '12 in', '16 in'), cut('Under-table braces', 2, '3/4 in', '3 in', '24 in')] } },
  { test: /router table fence/i, plan: { size: '32 × 5 in fence with 6 in base', metric: '813 × 127 mm fence with 152 mm base', stock: '3/4 in plywood or MDF core with straight laminate faces', joinery: 'square L-fence with independently adjustable sub-fences and dust port', finish: 'low-friction laminate on work faces', cutList: [cut('Fence face core', 1, '3/4 in', '5 in', '32 in'), cut('Fence base', 1, '3/4 in', '6 in', '32 in'), cut('Adjustable faces', 2, '1/2 in', '4 in', '15 in'), cut('Triangle braces', 4, '3/4 in', '5 in', '5 in')] } },
  { test: /CNC dust shoe/i, plan: { size: 'fit the actual spindle and 2-1/2 in hose', metric: 'fit the actual spindle and 64 mm hose', stock: '1/2 in plywood or clear acrylic body with replaceable brush strip', joinery: 'split clamp or magnetic lower plate that clears collet and full Z travel', finish: 'leave clearances unfinished; seal plywood edges only', cutList: [cut('Upper body', 1, '1/2 in', '6 in', '8 in'), cut('Replaceable lower plate', 2, '1/4 in', '6 in', '8 in'), cut('Brush strip', 1, '2 in', 'Perimeter', 'Fit perimeter'), cut('Spindle clamp test blank', 1, '1/2 in', '4 in', '6 in')] } },
  { test: /flat-pack furniture joinery on a CNC/i, plan: { size: '24 × 24 × 18 in test cabinet', metric: '610 × 610 × 457 mm test cabinet', stock: 'one measured sheet of stable 3/4 in plywood plus setup coupons', joinery: 'dog-bone or T-bone compensated slots tested against actual sheet thickness', finish: commonFinish, cutList: [cut('Sides', 2, 'Actual sheet', '18 in', '24 in'), cut('Top and bottom', 2, 'Actual sheet', '18 in', '22-1/2 in'), cut('Back stretcher', 1, 'Actual sheet', '6 in', '22-1/2 in'), cut('Joinery coupons', 6, 'Actual sheet', '3 in', '6 in')] } },
  { test: /router sled for flattening slabs/i, plan: { size: 'rails 12 in longer and bridge 6 in wider than the slab', metric: 'rails 305 mm longer and bridge 152 mm wider than the slab', stock: 'straight rigid rails and a stable plywood or metal router bridge', joinery: 'parallel leveled rails with a bridge that cannot lift or contact the cutter', finish: 'wax bearing surfaces only; keep stock supports high-friction', cutList: [cut('Leveling rails', 2, '1-1/2 in', '4 in', 'Slab + 12 in'), cut('Bridge sides', 2, '3/4 in', '4 in', 'Slab width + 6 in'), cut('Router base plate', 1, '1/2 in', '10 in', '14 in'), cut('Leveling shims', 12, 'Varies', '2 in', '4 in')] } },
  { test: /drill press table/i, plan: { size: '24 × 16 in top', metric: '610 × 406 mm top', stock: 'two-layer plywood or MDF top with straight fence and replaceable center insert', joinery: 'laminated top clamped to factory table with T-track fence', finish: 'durable low-friction top; leave insert replaceable', cutList: [cut('Top layers', 2, '3/4 in', '16 in', '24 in'), cut('Fence', 1, '3/4 in', '3 in', '24 in'), cut('Replaceable inserts', 4, '1/2 in', '4 in', '4 in'), cut('Clamp cleats', 2, '3/4 in', '2 in', '12 in')] } },
  { test: /turn a lidded box/i, plan: { size: '3 × 3 × 5 in blank', metric: '76 × 76 × 127 mm blank', stock: 'sound, dry, straight-grained hardwood turning blank', joinery: 'one blank parted into body and lid with a fitted tenon or recess', finish: 'apply a turning-safe finish with the lathe stopped unless its instructions say otherwise', cutList: [cut('Box blank', 1, '3 in', '3 in', '5 in'), cut('Practice blank', 1, '2-1/2 in', '2-1/2 in', '4 in'), cut('Finish sample', 1, '3/4 in', '2 in', '4 in')] } },
  { test: /Moxon vise/i, plan: { size: '24 in jaw capacity; hardware spacing from actual screws', metric: '610 mm jaw capacity', stock: 'two straight 8/4 hardwood jaws and a stable mounting cleat', joinery: 'rated vise screws through relieved rear jaw with bolted or clamped base', finish: 'oil or wax exterior surfaces; keep clamping faces high-friction', cutList: [cut('Front jaw', 1, '1-3/4 in', '5 in', '30 in'), cut('Rear jaw', 1, '1-3/4 in', '5 in', '30 in'), cut('Bench cleat', 1, '1-1/2 in', '4 in', '30 in'), cut('Spacer blocks', 2, '3/4 in', '3 in', '4 in')] } },
  { test: /planing stop and doe’s foot/i, plan: { size: '12 in stop plus 12 × 6 in doe’s foot', metric: '305 mm stop plus 305 × 152 mm doe’s foot', stock: 'straight hardwood scrap with 1/2 in plywood doe’s foot', joinery: 'removable bench stop and notched hold-down used with a separate holdfast', finish: 'leave all work-contact surfaces unfinished', cutList: [cut('Planing stop', 1, '1 in', '2 in', '12 in'), cut('Doe’s foot', 1, '1/2 in', '6 in', '12 in'), cut('Bench hook cleat', 1, '3/4 in', '2 in', '6 in')] } },
  { test: /portable workbench top for a folding table/i, plan: { size: '48 × 24 × 3 in workholding top', metric: '1219 × 610 × 76 mm top', stock: 'two layers of 3/4 in plywood with straight ribs and captured anti-slip cleats', joinery: 'laminated torsion-box top that clamps positively to the rated folding base', finish: 'seal lightly; leave dog holes and clamp edges free of slippery buildup', cutList: [cut('Top and bottom skins', 2, '3/4 in', '24 in', '48 in'), cut('Long ribs', 3, '3/4 in', '2 in', '46-1/2 in'), cut('Cross ribs', 5, '3/4 in', '2 in', '22-1/2 in'), cut('Underside locating cleats', 4, '3/4 in', '2 in', '10 in')] } },
  { test: /clamp rack|mobile clamp cart/i, plan: { size: '36 × 12 × 48 in high', metric: '914 × 305 × 1219 mm high', stock: '3/4 in plywood back or frame with doubled hardwood support arms', joinery: 'triangulated arms and back tied into wall framing or a wide rated mobile base', finish: 'clear finish for cleanability; keep clamp-contact edges durable', cutList: [cut('Back panel or frame', 1, '3/4 in', '36 in', '48 in'), cut('Support arms', 12, '1-1/2 in', '3 in', '12 in'), cut('Arm gussets', 12, '3/4 in', '6 in', '8 in'), cut('Base', 1, '3/4 in', '18 in', '36 in', 'Use only for mobile version with rated locking casters')] } },
  { test: /T-track stop block/i, plan: { size: '4 × 3 × 2 in block; fit actual track', metric: '102 × 76 × 51 mm block', stock: 'stable hardwood or laminated plywood with rated T-bolt hardware', joinery: 'square reference face locked by two points or a no-pivot body', finish: 'wax the track-contact face lightly', cutList: [cut('Stop body laminations', 2, '3/4 in', '3 in', '4 in'), cut('Reference face', 1, '1/2 in', '2 in', '4 in'), cut('Setup spacer', 1, '1/4 in', '2 in', '3 in')] } },
  { test: /right-angle assembly jig|corner-clamping jig/i, plan: { size: '8 × 8 in reference legs', metric: '203 × 203 mm reference legs', stock: '3/4 in stable plywood or MDF with relieved clamp corners', joinery: 'two verified square legs joined with gusset clear of clamp paths', finish: 'leave reference faces unfinished and check them for glue buildup', cutList: [cut('Reference legs', 2, '3/4 in', '4 in', '8 in'), cut('Gusset', 1, '3/4 in', '5 in', '5 in'), cut('Clamp relief blocks', 2, '3/4 in', '2 in', '3 in')] } },
  { test: /clamping cauls/i, plan: { size: '36 × 2 × 1-1/2 in each', metric: '914 × 51 × 38 mm each', stock: 'straight, dry 8/4 hardwood or laminated plywood strips', joinery: 'matched pair with a slight central crown and packing-tape release surface', finish: 'wax or tape only the glue-facing edge', cutList: [cut('Cauls', 2, '1-1/2 in', '2 in', '36 in'), cut('Crown setup strip', 1, '1/16 in', '1 in', '6 in'), cut('Glue-release faces', 2, 'Tape or film', '2 in', '36 in')] } },
  { test: /sanding-disc jig/i, plan: { size: '12 × 8 in table', metric: '305 × 203 mm table', stock: '3/4 in plywood table with straight adjustable fence and miter runner', joinery: 'pivoting fence referenced to the disc with positive angle stops', finish: 'wax table lightly while retaining work control', cutList: [cut('Table', 1, '3/4 in', '8 in', '12 in'), cut('Fence', 1, '3/4 in', '2 in', '10 in'), cut('Runner', 1, 'Fit slot', 'Fit slot', '10 in'), cut('Angle blocks', 3, '3/4 in', '2 in', '3 in')] } },
  { test: /flip-top tool cart|mobile planer cart|mobile table saw workstation/i, plan: { size: '30 × 24 × machine-working-height', metric: '762 × 610 mm × machine-working-height', stock: '3/4 in plywood case with doubled top pivots or machine platform and rated locking casters', joinery: 'racking-resistant box with through-bolted machine mounts and rated hardware', finish: 'durable clear finish while preserving machine ventilation and service access', cutList: [cut('Sides', 2, '3/4 in', '24 in', 'Set to machine height'), cut('Base', 1, '3/4 in', '24 in', '28-1/2 in'), cut('Machine platform', 1, '1-1/2 in', '24 in', '30 in'), cut('Back or diagonal braces', 1, '1/2 in', '28-1/2 in', 'Set to case'), cut('Caster blocking', 4, '1-1/2 in', '4 in', '4 in')] } },
  { test: /lumber cart|plywood storage rack|lumber rack|offcut organizer|scrap-wood sorting cart/i, plan: { size: '48 × 24 × 72 in high starting rack', metric: '1219 × 610 × 1829 mm high', stock: '3/4 in plywood dividers with structural-lumber base and rated anchors or casters', joinery: 'triangulated frame with retained bays sized to the actual stock and rated load', finish: 'seal for cleanability and keep floor-contact edges dry', cutList: [cut('Base rails', 2, '1-1/2 in', '3-1/2 in', '48 in'), cut('Cross rails', 4, '1-1/2 in', '3-1/2 in', '21 in'), cut('Vertical frames', 3, '3/4 in', '24 in', '72 in'), cut('Dividers or arms', 8, '3/4 in', '4 in', '24 in'), cut('Retaining lip', 1, '3/4 in', '4 in', '48 in')] } },
  { test: /tool wall|charging station|hand-tool cabinet|sandpaper storage cabinet|finishing-supply cabinet|shop-vac accessory dock|garden tool rack|wall cabinet for router bits/i, plan: { size: '36 × 8 × 48 in high starting cabinet', metric: '914 × 203 × 1219 mm high', stock: '3/4 in plywood or solid cleat field with 1/2 in back and tool-specific holders', joinery: 'square wall case or French-cleat panels anchored into verified framing', finish: 'durable clear finish; preserve ventilation and chemical-storage rules named in the title', cutList: [cut('Sides', 2, '3/4 in', '8 in', '48 in'), cut('Top and bottom', 2, '3/4 in', '8 in', '34-1/2 in'), cut('Back', 1, '1/2 in', '36 in', '48 in'), cut('Adjustable shelves or cleats', 5, '3/4 in', '6 in', '34-1/2 in'), cut('Tool-specific holders', 8, '3/4 in', '3 in', '8 in', 'Template from the actual tools or supplies')] } },
  { test: /fold-down assembly table/i, plan: { size: '48 × 30 in top at 34 in working height', metric: '1219 × 762 mm top at 864 mm height', stock: 'torsion-box plywood top with rated folding brackets or hinged legs', joinery: 'continuous wall cleat into framing with a positive open-position support', finish: 'durable low-friction top and sealed edges', cutList: [cut('Top skins', 2, '1/2 in', '30 in', '48 in'), cut('Long ribs', 3, '3/4 in', '2 in', '46-1/2 in'), cut('Cross ribs', 5, '3/4 in', '2 in', '28-1/2 in'), cut('Wall cleat', 1, '1-1/2 in', '4 in', '48 in'), cut('Folding legs or brackets', 2, 'Rated', 'Rated', 'Set to height')] } },
  { test: /ceiling-mounted storage rack/i, plan: { size: '48 × 24 in shelf; drop and load set by structure', metric: '1219 × 610 mm shelf', stock: '3/4 in plywood deck on a straight frame with rated threaded or structural hangers', joinery: 'through-bolted frame connected to verified ceiling framing; no drywall-only support', finish: 'seal exposed wood; keep inspection points visible', cutList: [cut('Shelf deck', 1, '3/4 in', '24 in', '48 in'), cut('Long frame rails', 2, '1-1/2 in', '3-1/2 in', '48 in'), cut('Cross rails', 4, '1-1/2 in', '3-1/2 in', '21 in'), cut('Hangers', 4, 'Rated', 'Rated', 'Set drop', 'Size and connect from verified structural design')] } },
  { test: /cyclone separator cart/i, plan: { size: '24 × 18 × 36 in high; fit actual vacuum and separator', metric: '610 × 457 × 914 mm high', stock: '3/4 in plywood base and uprights with rated casters and hose restraints', joinery: 'low, wide cart with captured vacuum and separator bucket', finish: 'seal for cleanability; preserve cooling airflow and service access', cutList: [cut('Base', 1, '3/4 in', '18 in', '24 in'), cut('Uprights', 2, '3/4 in', '6 in', '32 in'), cut('Vacuum cradle', 2, '3/4 in', '4 in', '18 in'), cut('Separator shelf', 1, '3/4 in', '18 in', '18 in'), cut('Hose retainers', 3, '3/4 in', '3 in', '6 in')] } },
  { test: /shop-vac muffler cabinet/i, plan: { size: 'vacuum envelope plus manufacturer cooling clearance', metric: 'vacuum envelope plus manufacturer cooling clearance', stock: '3/4 in plywood shell with removable acoustic baffles and unrestricted cooling passages', joinery: 'removable service panels and labyrinth baffles that never recirculate hot exhaust', finish: 'seal dust surfaces; do not line motor area with combustible loose foam', cutList: [cut('Side panels', 2, '3/4 in', 'Vacuum depth + clearance', 'Vacuum height + clearance'), cut('Top and bottom', 2, '3/4 in', 'Vacuum depth + clearance', 'Vacuum width + clearance'), cut('Removable back', 1, '3/4 in', 'Vacuum width + clearance', 'Vacuum height + clearance'), cut('Baffles', 3, '1/2 in', 'Size passage', 'Size passage')] } },
  { test: /overarm table saw dust hood/i, plan: { size: '36 in adjustable arm with hood sized to blade guard area', metric: '914 mm adjustable arm', stock: 'rigid plywood or metal arm with clear hood and supported hose', joinery: 'pivoting arm that cannot fall into the blade and preserves the factory guard', finish: 'seal wood; maintain visibility and smooth dust path', cutList: [cut('Vertical mast laminations', 2, '3/4 in', '3 in', '36 in'), cut('Horizontal arm laminations', 2, '3/4 in', '3 in', '36 in'), cut('Pivot plates', 4, '1/2 in', '5 in', '8 in'), cut('Clear hood panels', 4, '1/8–1/4 in', 'Fit blade area', 'Fit blade area')] } },
  { test: /downdraft sanding table/i, plan: { size: '30 × 20 × 6 in plenum', metric: '762 × 508 × 152 mm plenum', stock: '3/4 in plywood box with replaceable perforated top and sealed dust port', joinery: 'airtight plenum with interior baffles and removable cleanout', finish: 'seal interior surfaces and ground/handle dust equipment per manufacturer guidance', cutList: [cut('Perforated top', 1, '1/2 in', '20 in', '30 in'), cut('Bottom', 1, '3/4 in', '20 in', '30 in'), cut('Long sides', 2, '3/4 in', '6 in', '30 in'), cut('Ends', 2, '3/4 in', '6 in', '18-1/2 in'), cut('Baffles', 3, '1/2 in', '5 in', '18-1/2 in')] } },
  { test: /push-block and push-stick safety set/i, plan: { size: 'three tools sized to the actual machine and stock', metric: 'three tools sized to the actual machine and stock', stock: 'straight-grained hardwood or stable plywood with high-friction replaceable soles', joinery: 'one-piece handles or mechanically secured grips kept clear of the cutter path', finish: 'bright durable finish on handles; leave replaceable soles high-friction', cutList: [cut('Narrow-rip push stick', 1, '1/2 in', '4 in', '16 in'), cut('Heel push block', 1, '3/4 in', '5 in', '12 in'), cut('Jointer push pads', 2, '3/4 in', '5 in', '8 in'), cut('Replaceable heels', 4, '1/2 in', '1 in', '4 in')] } },
  { test: /magnetic task light/i, plan: { size: '24 in articulated reach', metric: '610 mm articulated reach', stock: 'hardwood arm links, guarded low-voltage fixture, rated magnets, and captured hardware', joinery: 'bolted pivots with locknuts and mechanical restraint independent of magnet where falling is hazardous', finish: 'fully cured finish kept away from heat and electrical connections', cutList: [cut('Arm links', 3, '3/4 in', '1-1/2 in', '8 in'), cut('Pivot blocks', 4, '3/4 in', '2 in', '2 in'), cut('Magnet housing', 1, '3/4 in', '3 in', '4 in'), cut('Lamp mount', 1, '3/4 in', '2 in', '4 in')] } },
  { test: /hand-sanding block set/i, plan: { size: 'four blocks from 2 × 4 to 3 × 8 in', metric: 'four blocks from 51 × 102 to 76 × 203 mm', stock: 'flat hardwood or plywood blocks with cork or rubber faces', joinery: 'one-piece blocks with replaceable abrasive retention', finish: 'seal hand-contact surfaces; leave pad faces clean', cutList: [cut('Quarter-sheet block', 1, '3/4 in', '3 in', '5-1/2 in'), cut('Contour blocks', 2, '3/4 in', '2 in', '4 in'), cut('Long-grain block', 1, '3/4 in', '2-1/2 in', '8 in'), cut('Cork faces', 4, '1/8 in', 'Fit block', 'Fit block')] } },
  { test: /finish sample board library/i, plan: { size: 'twelve 3 × 8 in samples plus indexed storage box', metric: 'twelve 76 × 203 mm samples', stock: 'offcuts from the actual species and sheet goods used in the shop', joinery: 'individual labeled samples stored on a bolt, ring, or divided box', finish: 'each sample carries a complete recorded schedule on its back', cutList: [cut('Sample boards', 12, 'Match project', '3 in', '8 in'), cut('Unfinished control boards', 3, 'Match project', '3 in', '8 in'), cut('Index dividers', 6, '1/4 in', '4 in', '9 in'), cut('Storage box panels', 5, '1/2 in', 'Fit samples', 'Fit samples')] } },
  { test: /round coffee table/i, plan: { size: '36 in diameter × 18 in high', metric: '914 mm diameter × 457 mm high', stock: '4/4 hardwood or veneered plywood top with a rigid three- or four-point base', joinery: 'segmented or frame base with movement-friendly top fasteners', finish: commonFinish, cutList: [cut('Top blank', 1, '3/4–1 in', '38 in', '38 in'), cut('Base legs', 4, '1-1/2 in', '2 in', '17 in'), cut('Base rails', 4, '3/4 in', '3 in', '20 in'), cut('Circle-jig test blank', 1, '1/2 in', '12 in', '12 in')] } },
  { test: /lift-top coffee table/i, plan: { size: '42 × 24 × 18 in closed', metric: '1067 × 610 × 457 mm closed', stock: '3/4 in cabinet plywood case with hardwood edging and rated lift hardware', joinery: 'square storage case with lift mechanism installed from its current drawing', finish: commonFinish, cutList: [cut('Lift top', 1, '3/4 in', '24 in', '42 in'), cut('Case sides', 2, '3/4 in', '16 in', '40 in'), cut('Case ends', 2, '3/4 in', '16 in', '22-1/2 in'), cut('Case bottom', 1, '3/4 in', '22-1/2 in', '40 in'), cut('Lift-mechanism mounting blocks', 2, '1-1/2 in', '4 in', '16 in')] } },
  { test: /hall tree/i, plan: { size: '42 × 18 × 72 in high', metric: '1067 × 457 × 1829 mm high', stock: '3/4 in plywood or straight hardwood frame with bench and cubbies', joinery: 'racking-resistant back and seat frame anchored to verified wall structure', finish: commonFinish, cutList: [cut('Tall sides', 2, '3/4 in', '18 in', '72 in'), cut('Bench seat', 1, '3/4–1 in', '18 in', '40-1/2 in'), cut('Shoe shelves', 2, '3/4 in', '16 in', '40-1/2 in'), cut('Back panel', 1, '1/2 in', '42 in', '72 in'), cut('Upper shelf', 1, '3/4 in', '12 in', '40-1/2 in')] } },
  { test: /record console|media console|TV console|turntable stand/i, plan: { size: '60 × 18 × 28 in high', metric: '1524 × 457 × 711 mm high', stock: '3/4 in cabinet plywood or hardwood case with a racking-resistant back', joinery: 'dados or loose tenons with sliding-door tracks or hardware fitted from actual components', finish: commonFinish, cutList: [cut('Top and bottom', 2, '3/4 in', '18 in', '60 in'), cut('Sides', 2, '3/4 in', '18 in', '27-1/4 in'), cut('Dividers', 2, '3/4 in', '17-1/2 in', '26-1/2 in'), cut('Back or stretchers', 1, '1/2 in', '60 in', '27-1/4 in'), cut('Doors', 2, '3/4 in', 'Fit opening', 'Fit opening')] } },
  { test: /speaker stand/i, plan: { size: '10 × 12 × 24 in high; top sized to speaker', metric: '254 × 305 × 610 mm high', stock: '3/4 in plywood or MDF column with doubled top and base', joinery: 'sealed hollow column with removable fill port and wide stable base', finish: commonFinish, cutList: [cut('Top plates', 2, '3/4 in', '10 in', '12 in'), cut('Base plates', 2, '3/4 in', '14 in', '16 in'), cut('Column sides', 4, '3/4 in', '6 in', '22-1/2 in'), cut('Fill-port plugs', 2, '3/4 in', '2 in', '2 in')] } },
  { test: /ladder shelf|blanket ladder/i, plan: { size: '24 × 12 × 72 in high', metric: '610 × 305 × 1829 mm high', stock: 'straight hardwood or construction lumber rails with sound shelf or rung stock', joinery: 'housed or doweled rungs with positive anti-tip wall restraint', finish: commonFinish, cutList: [cut('Side rails', 2, '1-1/2 in', '2-1/2 in', '72 in'), cut('Rungs or shelves', 5, '3/4–1 in', '8–12 in', '20 in'), cut('Wall spacers', 2, '3/4 in', '2 in', '4 in')] } },
  { test: /solid-wood bookcase|modular cube bookcase|barrister-style bookcase/i, plan: { size: '36 × 12 × 72 in high', metric: '914 × 305 × 1829 mm high', stock: '3/4 in cabinet plywood or straight 4/4 hardwood with a racking-resistant back', joinery: 'dados or adjustable pins with fixed structural shelves and anti-tip anchoring', finish: commonFinish, cutList: [cut('Sides', 2, '3/4 in', '12 in', '72 in'), cut('Top and bottom', 2, '3/4 in', '12 in', '34-1/2 in'), cut('Shelves', 5, '3/4 in', '11-1/2 in', '34-1/2 in'), cut('Back', 1, '1/4–1/2 in', '36 in', '72 in'), cut('Front edging', 7, '3/4 in', '1-1/2 in', '36 in')] } },
  { test: /sofa arm tray/i, plan: { size: '12 in long; width fitted to actual sofa arm', metric: '305 mm long; width fitted to actual sofa arm', stock: 'one straight 1×8 hardwood board or equivalent', joinery: 'three-piece U shape with splines, dowels, or reinforced miters', finish: 'fully cured, wipe-resistant furniture finish', cutList: [cut('Top', 1, '3/4 in', 'Arm width + 1-1/2 in', '12 in'), cut('Sides', 2, '3/4 in', '4 in', '12 in'), cut('Fit sample', 1, '1/4 in', '6 in', '8 in')] } },
  { test: /dining table/i, plan: { size: '72 × 36 × 30 in high baseline', metric: '1829 × 914 × 762 mm high', stock: 'dry 5/4 hardwood top stock with straight 8/4 leg or pedestal stock', joinery: 'mortise-and-tenon or loose-tenon base with movement-friendly top fasteners and knock-down hardware where named', finish: 'durable table finish proven on the same wood and allowed to cure fully', cutList: [cut('Top boards', 5, '1 in', '7–8 in', '74 in'), cut('Legs or pedestal components', 4, '2 in', '2 in', '29 in'), cut('Long aprons', 2, '3/4 in', '4 in', '65 in'), cut('End aprons', 2, '3/4 in', '4 in', '29 in'), cut('Top attachment rails', 2, '3/4 in', '2 in', '29 in'), cut('Finish and joinery samples', 2, 'Match project', '4 in', '12 in')] } },
  { test: /folding card table|drop-leaf table|converts into a dining table|counter-height bar table/i, plan: { size: '36 × 36 × 30 in baseline; revise height for bar use', metric: '914 × 914 × 762 mm baseline', stock: '4/4 hardwood top and straight leg stock with hardware matched to the folding action', joinery: 'rigid central base with rated hinges, pivots, locks, or rule joints fitted from actual hardware', finish: commonFinish, cutList: [cut('Center top', 1, '3/4–1 in', '24 in', '36 in'), cut('Leaves', 2, '3/4–1 in', '6 in', '36 in'), cut('Legs', 4, '1-1/2 in', '1-1/2 in', '29 in'), cut('Aprons', 4, '3/4 in', '3 in', '29 in'), cut('Swing supports', 2, '3/4 in', '3 in', '24 in')] } },
  { test: /child’s table and chair set/i, plan: { size: 'table 28 × 20 × 20 in; chair seat 12 in high', metric: 'table 711 × 508 × 508 mm; chair seat 305 mm high', stock: 'straight hardwood or cabinet plywood with rounded solid edging', joinery: 'conservative apron-and-leg frames with captured seat and anti-tip proportions', finish: 'fully cured low-odor finish selected for expected contact and cleaning', cutList: [cut('Table top', 1, '3/4 in', '20 in', '28 in'), cut('Table legs', 4, '1-1/2 in', '1-1/2 in', '19-1/4 in'), cut('Chair seats', 2, '3/4 in', '12 in', '12 in'), cut('Chair legs', 8, '1-1/4 in', '1-1/4 in', '11-1/4 in'), cut('Aprons and rails', 12, '3/4 in', '2-1/2 in', 'Fit frames')] } },
  { test: /folding camp stool/i, plan: { size: '18 × 16 × 18 in open', metric: '457 × 406 × 457 mm open', stock: 'straight hardwood legs, rated pivot bolts, and durable seat canvas', joinery: 'two crossed leg frames with captured pivots and reinforced sewn seat', finish: 'fully cure finish before installing fabric; keep pivot bearing surfaces clean', cutList: [cut('Legs', 4, '1 in', '2 in', '22 in'), cut('Upper rails', 2, '1 in', '1-1/2 in', '16 in'), cut('Lower stretchers', 2, '1 in', '1-1/2 in', '14 in'), cut('Canvas seat', 1, 'Fabric', '18 in', '22 in')] } },
  { test: /blanket chest|wardrobe trunk/i, plan: { size: '40 × 20 × 20 in high', metric: '1016 × 508 × 508 mm high', stock: '3/4 in plywood or frame-and-panel hardwood with a captured bottom', joinery: 'racking-resistant case with current soft-close lid supports and ventilation where needed', finish: commonFinish, cutList: [cut('Front and back', 2, '3/4 in', '18 in', '40 in'), cut('Ends', 2, '3/4 in', '18 in', '18-1/2 in'), cut('Bottom', 1, '3/4 in', '18-1/2 in', '38-1/2 in'), cut('Lid', 1, '3/4 in', '20 in', '40 in'), cut('Lid-support blocking', 2, '1-1/2 in', '3 in', '8 in')] } },
  { test: /dresser drawers/i, plan: { size: 'fit the measured dresser openings and exact slide clearance', metric: 'fit the measured dresser openings and exact slide clearance', stock: '1/2 in drawer sides with 1/4 in bottoms and 3/4 in applied fronts', joinery: 'locking rabbets or dovetails with bottom grooves and slide-specific clearance', finish: commonFinish, cutList: [cut('Drawer sides', 12, '1/2 in', '5–8 in', 'Opening depth'), cut('Drawer fronts and backs', 12, '1/2 in', '5–8 in', 'Opening minus side thickness'), cut('Drawer bottoms', 6, '1/4 in', 'Fit groove', 'Fit groove'), cut('Applied fronts', 6, '3/4 in', 'Fit reveal', 'Fit reveal')] } },
  { test: /clothing rack|closet organizer/i, plan: { size: '48 × 20 × 72 in high', metric: '1219 × 508 × 1829 mm high', stock: '3/4 in cabinet plywood or straight hardwood frame with rated clothes rod', joinery: 'racking-resistant case or braced frame anchored to verified wall structure', finish: commonFinish, cutList: [cut('Tall sides', 2, '3/4 in', '20 in', '72 in'), cut('Top and shoe shelves', 3, '3/4 in', '19-1/2 in', '46-1/2 in'), cut('Back or braces', 1, '1/2 in', '48 in', '72 in'), cut('Clothes rod', 1, 'Rated', 'Rated', '46 in')] } },
  { test: /under-bed storage drawers/i, plan: { size: 'two 36 × 30 × 8 in boxes; verify bed clearance', metric: 'two 914 × 762 × 203 mm boxes', stock: '1/2 in plywood boxes with 1/4 in bottoms and low rated casters', joinery: 'rabbeted square boxes with captured bottoms and applied fronts', finish: commonFinish, cutList: [cut('Long sides', 4, '1/2 in', '7 in', '36 in'), cut('Ends', 4, '1/2 in', '7 in', '29 in'), cut('Bottoms', 2, '1/4 in', '29 in', '35 in'), cut('Applied fronts', 2, '3/4 in', '8 in', '38 in')] } },
  { test: /bookcase desk wall/i, plan: { size: '96 × 24 × 84 in overall; 30 in desk height', metric: '2438 × 610 × 2134 mm overall; 762 mm desk height', stock: 'modular 3/4 in plywood bookcases with 1/2 in backs and a movement-stable desktop', joinery: 'individually square cases connected to one another and anchored to verified wall structure', finish: commonFinish, cutList: [cut('Tall case sides', 4, '3/4 in', '12 in', '84 in'), cut('Case tops and bottoms', 4, '3/4 in', '12 in', '22-1/2 in'), cut('Shelves', 10, '3/4 in', '11-1/2 in', '22-1/2 in'), cut('Backs', 2, '1/2 in', '24 in', '84 in'), cut('Desktop', 1, '3/4–1 in', '24 in', '48 in'), cut('Desktop cleats', 2, '1-1/2 in', '3 in', '24 in')] } },
  { test: /Murphy desk/i, plan: { size: '32 × 8 × 42 in closed; 30 in desk height open', metric: '813 × 203 × 1067 mm closed; 762 mm open height', stock: '3/4 in plywood wall case and desktop with rated pivots, stays, and listed low-voltage lighting', joinery: 'racking-resistant wall case anchored to framing with positive open and closed stops', finish: commonFinish, cutList: [cut('Case sides', 2, '3/4 in', '8 in', '42 in'), cut('Case top and bottom', 2, '3/4 in', '8 in', '30-1/2 in'), cut('Fold-down desktop', 1, '3/4 in', '30 in', '31 in'), cut('Back', 1, '1/2 in', '32 in', '42 in'), cut('Support stays', 2, 'Rated', 'Rated', 'Fit hardware')] } },
  { test: /desktop that won’t cup/i, plan: { size: '60 × 30 × 1 in top', metric: '1524 × 762 × 25 mm top', stock: 'straight 5/4 hardwood boards conditioned to the room', joinery: 'long-grain panel glue-up attached through slotted holes or movement-friendly hardware', finish: 'apply the same schedule to both faces and edges after a labeled sample', cutList: [cut('Top boards', 5, '1 in', '6–7 in', '62 in'), cut('Setup cauls', 4, '1-1/2 in', '2 in', '36 in'), cut('Finish sample', 1, '1 in', '3 in', '12 in')] } },
  { test: /standing desk base with electric legs/i, plan: { size: '60 × 30 in desktop; base from current hardware drawing', metric: '1524 × 762 mm desktop', stock: '3/4–1 in stable top with manufacturer-approved electric base and fasteners', joinery: 'threaded inserts or screws in manufacturer locations with cable strain relief', finish: commonFinish, cutList: [cut('Desktop', 1, '3/4–1 in', '30 in', '60 in'), cut('Under-top mounting blocks', 2, '3/4 in', '4 in', '24 in'), cut('Cable tray', 1, '1/2 in', '5 in', '42 in'), cut('Control mounting plate', 1, '1/2 in', '4 in', '8 in')] } },
  { test: /monitor riser/i, plan: { size: '36 × 10 × 5 in high', metric: '914 × 254 × 127 mm high', stock: '3/4 in hardwood or cabinet plywood', joinery: 'dadoed or splined U-shaped riser with center support if required by load', finish: commonFinish, cutList: [cut('Top', 1, '3/4 in', '10 in', '36 in'), cut('Ends', 2, '3/4 in', '10 in', '4-1/4 in'), cut('Center divider', 1, '3/4 in', '10 in', '4-1/4 in'), cut('Keyboard stop', 1, '1/4 in', '1 in', '34-1/2 in')] } },
  { test: /laptop stand/i, plan: { size: '12 × 10 in platform with 15–35° adjustment', metric: '305 × 254 mm platform', stock: '1/2 in plywood or hardwood platform with rated pivot and positive stops', joinery: 'hinged platform with captured adjustment bar and ventilation slots', finish: commonFinish, cutList: [cut('Platform', 1, '1/2 in', '10 in', '12 in'), cut('Base', 1, '1/2 in', '10 in', '12 in'), cut('Adjustment arms', 2, '1/2 in', '1-1/2 in', '8 in'), cut('Front stop', 1, '1/2 in', '1 in', '10 in')] } },
  { test: /desk organizer/i, plan: { size: '14 × 8 × 5 in high', metric: '356 × 203 × 127 mm high', stock: '1/2 in hardwood or plywood offcuts with 1/4 in dividers', joinery: 'rabbets or grooves with removable dividers', finish: commonFinish, cutList: [cut('Base', 1, '1/2 in', '8 in', '14 in'), cut('Long sides', 2, '1/2 in', '4 in', '14 in'), cut('Ends', 2, '1/2 in', '4 in', '7 in'), cut('Dividers', 4, '1/4 in', '3 in', '7 in')] } },
  { test: /headphone stand/i, plan: { size: '10 × 6 × 12 in high', metric: '254 × 152 × 305 mm high', stock: 'thin hardwood laminations over a full-size bending form with a weighted base', joinery: 'fully cured bent lamination housed in a broad base', finish: commonFinish, cutList: [cut('Arch laminations', 6, '1/8 in', '1-1/2 in', '24 in'), cut('Base', 1, '1 in', '6 in', '10 in'), cut('Bending form layers', 4, '3/4 in', '8 in', '14 in')] } },
  { test: /footrest/i, plan: { size: '18 × 12 in platform with 5–20° tilt', metric: '457 × 305 mm platform', stock: '3/4 in plywood platform with hardwood base and positive adjustment stops', joinery: 'pivoting platform with captured stop bar and non-slip feet', finish: commonFinish, cutList: [cut('Platform', 1, '3/4 in', '12 in', '18 in'), cut('Base rails', 2, '3/4 in', '3 in', '16 in'), cut('Pivot blocks', 2, '1-1/2 in', '2 in', '3 in'), cut('Adjustment bar', 1, '3/4 in', '1-1/2 in', '14 in')] } },
  { test: /cabinet doors|Shaker doors/i, plan: { size: 'fit the installed opening with the chosen overlay or inset reveal', metric: 'fit the installed opening with the chosen overlay or inset reveal', stock: 'straight 3/4 in rail-and-stile stock with stable 1/4 in panels', joinery: 'cope-and-stick, stub-tenon, or table-saw groove joinery proven in matching scrap', finish: commonFinish, cutList: [cut('Stiles', 2, '3/4 in', '2-1/4 in', 'Door height'), cut('Rails', 2, '3/4 in', '2-1/4 in', 'Door width minus stile/joinery allowance'), cut('Panel', 1, '1/4 in', 'Groove fit', 'Groove fit'), cut('Setup rails and stiles', 4, 'Match door', '3 in', '8 in')] } },
  { test: /drawer box|dovetailed drawer/i, plan: { size: 'fit the measured opening and exact slide clearance', metric: 'fit the measured opening and exact slide clearance', stock: '1/2 in straight hardwood or plywood sides with 1/4 in bottom', joinery: 'locking rabbets or dovetails with a captured bottom', finish: 'finish inside lightly before installing slides; keep glue surfaces clean', cutList: [cut('Sides', 2, '1/2 in', '4–6 in', 'Opening depth'), cut('Front and back', 2, '1/2 in', '4–6 in', 'Opening width minus side joinery'), cut('Bottom', 1, '1/4 in', 'Fit groove', 'Fit groove'), cut('Applied front', 1, '3/4 in', 'Fit reveal', 'Fit reveal')] } },
  { test: /kitchen island/i, plan: { size: '60 × 30 × 36 in high with 12 in seating overhang', metric: '1524 × 762 × 914 mm high with 305 mm overhang', stock: '3/4 in cabinet plywood bases with a rated, supported countertop', joinery: 'square anchored cases with overhang support sized by the top manufacturer', finish: 'durable fully cured finish appropriate to kitchen cleaning', cutList: [cut('Base sides', 4, '3/4 in', '24 in', '34-1/2 in'), cut('Base tops and bottoms', 4, '3/4 in', '24 in', '28-1/2 in'), cut('Backs', 2, '1/2 in', '30 in', '34-1/2 in'), cut('Countertop', 1, 'Per material', '30 in', '60 in'), cut('Overhang brackets', 3, 'Rated', 'Rated', 'Fit top')] } },
  { test: /butcher-block countertop/i, plan: { size: '72 × 25 × 1-1/2 in baseline', metric: '1829 × 635 × 38 mm baseline', stock: 'dry straight hardwood strips selected for a stable long-grain lamination', joinery: 'long-grain glue-up attached to cabinets through movement-friendly holes', finish: 'fully cured finish selected for the intended food, water, and maintenance exposure', cutList: [cut('Lamination strips', 12, '1-1/2 in', '2–3 in', '74 in'), cut('Backsplash or edge strip', 1, '1-1/2 in', '3 in', '74 in'), cut('Finish samples', 3, '1-1/2 in', '3 in', '8 in')] } },
  { test: /laundry pedestal/i, plan: { size: 'fit actual appliance footprint; 12 in high baseline', metric: 'fit actual appliance footprint; 305 mm high baseline', stock: '3/4 in cabinet plywood with doubled top and internal load-bearing partitions', joinery: 'glued and screwed structural box on a level floor; follow appliance installation requirements', finish: 'moisture-resistant fully cured finish', cutList: [cut('Doubled top', 2, '3/4 in', 'Appliance depth', 'Appliance width'), cut('Sides', 2, '3/4 in', 'Appliance depth', '10-1/2 in'), cut('Center partitions', 2, '3/4 in', 'Appliance depth', '10-1/2 in'), cut('Bottom', 1, '3/4 in', 'Appliance depth', 'Appliance width'), cut('Back braces', 2, '3/4 in', '4 in', 'Appliance width')] } },
  { test: /wall-mounted pot rack/i, plan: { size: '36 × 10 in rail frame', metric: '914 × 254 mm rail frame', stock: 'straight hardwood rails with rated hooks and wall hardware', joinery: 'braced rail frame or cleat anchored to verified studs or masonry', finish: 'fully cured cleanable finish; keep hook hardware accessible for inspection', cutList: [cut('Long rails', 2, '3/4 in', '3 in', '36 in'), cut('Cross rails', 3, '3/4 in', '3 in', '8-1/2 in'), cut('Wall cleat', 1, '1-1/2 in', '3 in', '34 in'), cut('Hook test block', 1, '1-1/2 in', '3 in', '6 in')] } },
  { test: /mudroom locker wall/i, plan: { size: '72 × 18 × 84 in high starting wall', metric: '1829 × 457 × 2134 mm high', stock: '3/4 in plywood locker cases with hardwood bench edging and racking-resistant backs', joinery: 'modular square cases anchored to verified wall structure', finish: commonFinish, cutList: [cut('Locker sides', 4, '3/4 in', '18 in', '84 in'), cut('Bench seat', 1, '1 in', '18 in', '72 in'), cut('Upper shelves', 3, '3/4 in', '16 in', '22-1/2 in'), cut('Back panels', 3, '1/2 in', '24 in', '84 in'), cut('Shoe dividers', 6, '3/4 in', '16 in', '16 in')] } },
  { test: /planter box/i, plan: { size: '36 × 14 × 16 in high', metric: '914 × 356 × 406 mm high', stock: '3/4 in cedar boards with replaceable liner and raised feet', joinery: 'exterior screws into corner cleats with drainage gaps and removable liner', finish: 'leave soil-side cedar unfinished or follow product guidance; finish exterior only', cutList: [cut('Long sides', 4, '3/4 in', '5-1/2 in', '36 in'), cut('Ends', 4, '3/4 in', '5-1/2 in', '12-1/2 in'), cut('Corner cleats', 4, '1-1/2 in', '1-1/2 in', '15 in'), cut('Bottom slats', 5, '3/4 in', '2-1/2 in', '12-1/2 in'), cut('Feet', 4, '1-1/2 in', '1-1/2 in', '3 in')] } },
  { test: /raised garden bed/i, plan: { size: '72 × 36 × 18 in high baseline', metric: '1829 × 914 × 457 mm high', stock: 'naturally durable or correctly treated exterior lumber compatible with the intended use', joinery: 'exterior structural screws through corner and mid-span posts with drainage to grade', finish: 'finish exterior only when desired and compatible; never trap water behind a liner', cutList: [cut('Long side boards', 6, '1-1/2 in', '5-1/2 in', '72 in'), cut('End boards', 6, '1-1/2 in', '5-1/2 in', '33 in'), cut('Corner posts', 4, '3-1/2 in', '3-1/2 in', '18 in'), cut('Mid-span posts', 2, '3-1/2 in', '3-1/2 in', '18 in'), cut('Top caps', 4, '3/4 in', '3-1/2 in', 'Fit frame')] } },
  { test: /potting bench/i, plan: { size: '48 × 24 × 36 in work surface; 72 in overall', metric: '1219 × 610 × 914 mm work surface; 1829 mm overall', stock: 'exterior-rated lumber with slatted lower shelf and removable soil bin', joinery: 'braced frame with water-shedding top and corrosion-resistant fasteners', finish: 'exterior finish with protected end grain and open drainage', cutList: [cut('Worktop slats', 6, '3/4 in', '4 in', '48 in'), cut('Front legs', 2, '1-1/2 in', '3-1/2 in', '35-1/4 in'), cut('Back legs', 2, '1-1/2 in', '3-1/2 in', '72 in'), cut('Aprons', 4, '3/4 in', '4 in', 'Fit frame'), cut('Shelf slats', 6, '3/4 in', '3 in', '20 in'), cut('Bin rails', 2, '3/4 in', '3 in', '24 in')] } },
  { test: /patio cooler cart/i, plan: { size: '36 × 20 × 34 in high; opening fitted to actual cooler', metric: '914 × 508 × 864 mm high', stock: 'exterior-rated lumber frame with removable cooler and corrosion-resistant hardware', joinery: 'braced rolling frame with drained cooler cradle and rated locking casters', finish: 'exterior finish with water-shedding joints and accessible drain', cutList: [cut('Legs', 4, '1-1/2 in', '3-1/2 in', '32 in'), cut('Long rails', 4, '3/4 in', '4 in', '30 in'), cut('End rails', 4, '3/4 in', '4 in', '14 in'), cut('Top slats', 6, '3/4 in', '3 in', '36 in'), cut('Cooler support rails', 2, '1-1/2 in', '3-1/2 in', '30 in'), cut('Lower shelf slats', 5, '3/4 in', '3 in', '16 in')] } },
  { test: /firewood rack/i, plan: { size: '48 × 18 × 48 in high with roof', metric: '1219 × 457 × 1219 mm high', stock: 'exterior structural lumber with raised slatted base and corrosion-resistant fasteners', joinery: 'braced side frames, ventilated base, and sloped rain-shedding roof', finish: 'exterior finish with sealed end grain and open airflow', cutList: [cut('Base rails', 2, '1-1/2 in', '3-1/2 in', '48 in'), cut('Uprights', 4, '1-1/2 in', '3-1/2 in', '44 in'), cut('Base slats', 6, '3/4 in', '3 in', '18 in'), cut('Roof rafters', 4, '1-1/2 in', '3-1/2 in', '22 in'), cut('Roof boards', 5, '3/4 in', '5-1/2 in', '52 in')] } },
  { test: /patio storage bench/i, plan: { size: '48 × 20 × 20 in high', metric: '1219 × 508 × 508 mm high', stock: 'exterior-rated lumber or plywood with ventilated storage and a sloped lid', joinery: 'braced box on raised feet with rated lid supports and drainage gaps', finish: 'exterior finish with all end grain and seams detailed to shed water', cutList: [cut('Front and back frames', 2, '3/4–1 in', '18 in', '48 in'), cut('End frames', 2, '3/4–1 in', '18 in', '18-1/2 in'), cut('Slatted bottom', 6, '3/4 in', '3 in', '46-1/2 in'), cut('Sloped lid', 1, '3/4–1 in', '21 in', '49 in'), cut('Raised feet', 4, '1-1/2 in', '2 in', '3 in')] } },
  { test: /outdoor sectional/i, plan: { size: 'each module 30 × 30 × 30 in high', metric: 'each module 762 × 762 × 762 mm high', stock: 'straight exterior-rated lumber with corrosion-resistant hardware', joinery: 'braced seat and back frames joined by removable module connectors', finish: 'exterior finish with drainage gaps and accessible inspection points', cutList: [cut('Seat rails', 4, '1-1/2 in', '3-1/2 in', '27 in'), cut('Seat slats', 7, '3/4 in', '3 in', '30 in'), cut('Front legs', 2, '1-1/2 in', '3-1/2 in', '16 in'), cut('Back legs', 2, '1-1/2 in', '3-1/2 in', '30 in'), cut('Back slats', 5, '3/4 in', '3 in', '27 in')] } },
  { test: /porch swing/i, plan: { size: '48 × 22 in seat; hanging geometry from rated hardware', metric: '1219 × 559 mm seat', stock: 'straight exterior-rated lumber with through-bolted hanging points', joinery: 'braced seat and back frame with rated connectors and independent hanging hardware', finish: 'exterior finish; inspect hanging points and end grain regularly', cutList: [cut('Seat rails', 4, '1-1/2 in', '3-1/2 in', '48 in'), cut('Seat slats', 7, '3/4 in', '3 in', '22 in'), cut('Back rails', 3, '1-1/2 in', '3-1/2 in', '48 in'), cut('Back slats', 8, '3/4 in', '3 in', '24 in'), cut('Hanging blocks', 4, '1-1/2 in', '4 in', '6 in')] } },
  { test: /hammock stand/i, plan: { size: '14 ft long × 4 ft wide baseline; size from hammock and rated design', metric: '4.27 × 1.22 m baseline', stock: 'straight structural exterior lumber with rated through-bolts and connectors', joinery: 'braced base and uprights from a verified load design; no screw-only end-grain load path', finish: 'exterior finish with regular bolt and split inspection', cutList: [cut('Base beams', 2, '1-1/2 in', '5-1/2 in', '8 ft'), cut('Angled uprights', 2, '1-1/2 in', '5-1/2 in', '8 ft'), cut('Cross feet', 2, '1-1/2 in', '5-1/2 in', '48 in'), cut('Gussets', 8, '3/4 in', '8 in', '12 in'), cut('Through-bolt spacers', 4, '1-1/2 in', '5-1/2 in', '12 in')] } },
  { test: /bird feeder/i, plan: { size: '12 × 10 × 12 in high', metric: '305 × 254 × 305 mm high', stock: '3/4 in untreated cedar with removable tray and easy-clean roof', joinery: 'exterior screws with drainage, ventilation, and tool-free cleanout', finish: 'leave food-contact and interior surfaces unfinished', cutList: [cut('Floor', 1, '3/4 in', '10 in', '12 in'), cut('Roof panels', 2, '3/4 in', '8 in', '14 in'), cut('End panels', 2, '3/4 in', '10 in', '10 in'), cut('Seed rails', 2, '3/4 in', '1-1/2 in', '12 in'), cut('Removable tray', 1, '1/4 in', '9 in', '11 in')] } },
  { test: /pollinator hotel/i, plan: { size: '18 × 6 × 24 in high', metric: '457 × 152 × 610 mm high', stock: 'untreated dry hardwood blocks and replaceable natural nesting tubes under a rain roof', joinery: 'compartmented weather-shedding frame with removable, maintainable inserts', finish: 'finish exterior roof and frame only; leave nesting material untreated', cutList: [cut('Back', 1, '3/4 in', '18 in', '24 in'), cut('Sides', 2, '3/4 in', '6 in', '22 in'), cut('Roof', 1, '3/4 in', '9 in', '20 in'), cut('Dividers', 4, '3/4 in', '5 in', '16-1/2 in'), cut('Replaceable nesting blocks', 8, '2–4 in', 'Fit bay', 'Fit bay')] } },
  { test: /compost-screening frame/i, plan: { size: '36 × 24 in screen', metric: '914 × 610 mm screen', stock: 'exterior cedar frame with corrosion-resistant 1/2 in hardware cloth', joinery: 'half-lapped or screwed frame that captures all sharp mesh edges', finish: 'exterior finish on frame only; keep mesh replaceable', cutList: [cut('Long frame rails', 4, '3/4 in', '3 in', '36 in'), cut('Short frame rails', 4, '3/4 in', '3 in', '18 in'), cut('Hardware cloth', 1, 'Mesh', '24 in', '36 in'), cut('Mesh retaining strips', 8, '1/4 in', '3/4 in', 'Fit frame')] } },
  { test: /outdoor serving tray with stand/i, plan: { size: 'tray 24 × 16 in; stand 28 in high', metric: 'tray 610 × 406 mm; stand 711 mm high', stock: 'exterior-rated hardwood with rated pivot bolts and removable tray', joinery: 'slatted tray with crossed folding leg frames and positive open stop', finish: 'fully cured exterior finish with drainage gaps', cutList: [cut('Tray bottom slats', 6, '3/4 in', '2-1/2 in', '22 in'), cut('Tray sides', 2, '3/4 in', '3 in', '24 in'), cut('Tray ends', 2, '3/4 in', '3 in', '14-1/2 in'), cut('Stand legs', 4, '1 in', '2 in', '32 in'), cut('Stand rails', 4, '1 in', '1-1/2 in', '16 in')] } },
  { test: /valet tray/i, plan: { size: '10 × 7 × 3/4 in', metric: '254 × 178 × 19 mm', stock: 'one clear 4/4 hardwood blank', joinery: 'shallow routed or carved pockets with generous inside radii', finish: 'fully cured low-sheen finish suitable for daily handling', cutList: [cut('Tray blank', 1, '3/4–1 in', '7 in', '10 in'), cut('Routing template', 1, '1/4 in', '7 in', '10 in'), cut('Finish sample', 1, '3/4 in', '2 in', '4 in')] } },
  { test: /vinyl record crate/i, plan: { size: '14-1/2 × 14 × 14 in high; verify actual sleeves', metric: '368 × 356 × 356 mm high', stock: '1/2 in plywood or hardwood sides with a 3/4 in reinforced bottom', joinery: 'rabbets or box joints with captured bottom and rounded handholds', finish: commonFinish, cutList: [cut('Front and back', 2, '1/2 in', '14 in', '14-1/2 in'), cut('Ends', 2, '1/2 in', '14 in', '13-1/2 in'), cut('Bottom', 1, '3/4 in', '13-1/2 in', '13-1/2 in'), cut('Handhold test panels', 2, '1/2 in', '5 in', '8 in')] } },
  { test: /key holder with mail shelf/i, plan: { size: '24 × 5 × 10 in high', metric: '610 × 127 × 254 mm high', stock: '3/4 in hardwood or plywood back with solid shelf and rated hooks', joinery: 'dadoed shelf and wall cleat anchored into verified structure', finish: commonFinish, cutList: [cut('Back', 1, '3/4 in', '10 in', '24 in'), cut('Mail shelf', 1, '3/4 in', '5 in', '24 in'), cut('Front lip', 1, '1/2 in', '2 in', '24 in'), cut('Wall cleat', 1, '3/4 in', '3 in', '22 in')] } },
  { test: /phone stand with charging slot/i, plan: { size: '4 × 6 × 7 in high; fit actual phone and cable', metric: '102 × 152 × 178 mm high', stock: '3/4 in hardwood with a wide stable base', joinery: 'angled housed back with cable slot and relieved connector path', finish: commonFinish, cutList: [cut('Base', 1, '3/4 in', '6 in', '7 in'), cut('Back', 1, '3/4 in', '4 in', '7 in'), cut('Front ledge', 1, '3/4 in', '1 in', '4 in'), cut('Cable-fit sample', 1, '3/4 in', '2 in', '4 in')] } },
  { test: /tablet stand/i, plan: { size: '10 × 8 × 10 in high; fit actual tablet and case', metric: '254 × 203 × 254 mm high', stock: '3/4 in hardwood or plywood with broad base and captured ledge', joinery: 'angled housed back or folding easel with positive stop', finish: commonFinish, cutList: [cut('Back', 1, '3/4 in', '8 in', '10 in'), cut('Base', 1, '3/4 in', '8 in', '10 in'), cut('Ledge', 1, '3/4 in', '1-1/2 in', '8 in'), cut('Angle test block', 1, '3/4 in', '3 in', '6 in')] } },
  { test: /desk lamp/i, plan: { size: '24 in articulated reach on 8 × 8 in base', metric: '610 mm reach on 203 × 203 mm base', stock: 'hardwood arm links with listed low-voltage fixture, cord, and captured hardware', joinery: 'bolted friction pivots and weighted base with cord strain relief', finish: 'fully cured finish kept clear of heat and electrical contacts', cutList: [cut('Arm links', 4, '3/4 in', '1-1/2 in', '8 in'), cut('Base', 1, '1 in', '8 in', '8 in'), cut('Pivot spacers', 6, '1/4 in', '1-1/2 in', '1-1/2 in'), cut('Fixture mount', 1, '3/4 in', '3 in', '4 in')] } },
  { test: /passive wooden phone speaker/i, plan: { size: '10 × 4 × 3 in; sound channel fitted to actual phone', metric: '254 × 102 × 76 mm', stock: 'three 3/4 in hardwood laminations or one thick clear blank', joinery: 'laminated body around a tested tapered sound channel and phone slot', finish: commonFinish, cutList: [cut('Body laminations', 3, '3/4 in', '4 in', '10 in'), cut('Phone-slot test pieces', 3, '3/4 in', '2 in', '5 in'), cut('Finish sample', 1, '3/4 in', '2 in', '4 in')] } },
  { test: /wooden wall clock/i, plan: { size: '14 in diameter × 3/4 in', metric: '356 mm diameter × 19 mm', stock: 'stable hardwood panel or veneered plywood sized to the actual clock movement', joinery: 'one-piece or laminated dial with rear movement recess and hanging hardware', finish: commonFinish, cutList: [cut('Dial blank', 1, '3/4 in', '15 in', '15 in'), cut('Numeral-layout template', 1, '1/4 in', '15 in', '15 in'), cut('Movement-recess test blank', 1, '3/4 in', '4 in', '6 in')] } },
  { test: /growth chart ruler/i, plan: { size: '6 × 72 × 3/4 in board', metric: '152 × 1829 × 19 mm board', stock: 'one straight, stable 1×8 board with wall standoffs or cleat', joinery: 'one-piece marked board hung from a repeatable floor offset into verified structure', finish: 'fully cured clear finish over permanent, measured markings', cutList: [cut('Chart board', 1, '3/4 in', '7-1/4 in', '72 in'), cut('Wall cleats', 2, '3/4 in', '2 in', '6 in'), cut('Marking sample', 1, '3/4 in', '3 in', '12 in')] } },
  { test: /wooden building blocks/i, plan: { size: '24-block set from 1-1/2 in modular units', metric: '24-block set from 38 mm modular units', stock: 'clear straight-grained hardwood without checks, knots, or splinters', joinery: 'one-piece blocks cut from shared stops with consistently rounded edges', finish: 'leave unfinished or use a fully cured finish selected for the child’s age and contact', cutList: [cut('Cubes', 8, '1-1/2 in', '1-1/2 in', '1-1/2 in'), cut('Double blocks', 8, '1-1/2 in', '1-1/2 in', '3 in'), cut('Quad blocks', 4, '1-1/2 in', '1-1/2 in', '6 in'), cut('Arch and triangle blanks', 4, '1-1/2 in', '3 in', '3 in'), cut('Setup and finish samples', 3, 'Match blocks', '2 in', '4 in')] } },
  { test: /toy car ramp/i, plan: { size: '36 × 12 × 12 in high', metric: '914 × 305 × 305 mm high', stock: '1/2 in plywood deck and sides with rounded hardwood edging', joinery: 'braced ramp with captured side rails and no detachable small parts', finish: 'fully cured finish selected for the child’s age and expected contact', cutList: [cut('Ramp deck', 1, '1/2 in', '12 in', '36 in'), cut('Side rails', 2, '1/2 in', '3 in', '36 in'), cut('Support triangles', 3, '3/4 in', '10 in', '12 in'), cut('Bottom stop', 1, '3/4 in', '2 in', '12 in')] } },
  { test: /kids’ step tower/i, plan: { size: '18 × 18 × 36 in high; platform set for intended child and counter', metric: '457 × 457 × 914 mm high', stock: '3/4 in cabinet plywood or straight hardwood with non-slip platform', joinery: 'braced side frames, captured platform, guard rails, and wide anti-tip footprint', finish: 'fully cured child-appropriate finish and replaceable non-slip surface', cutList: [cut('Side panels', 2, '3/4 in', '18 in', '36 in'), cut('Platform', 1, '3/4 in', '16-1/2 in', '16 in'), cut('Steps', 2, '3/4 in', '8 in', '16-1/2 in'), cut('Guard rails', 4, '1 in', '2 in', '18 in'), cut('Base stretchers', 3, '3/4 in', '4 in', '16-1/2 in')] } },
  { test: /pet feeding station/i, plan: { size: '24 × 12 × 8 in high; bowl openings from actual bowls', metric: '610 × 305 × 203 mm high', stock: '3/4 in water-resistant plywood or hardwood with removable bowls', joinery: 'braced stand with routed bowl openings and non-slip feet', finish: 'fully cured water-resistant finish; preserve easy-clean edges', cutList: [cut('Top', 1, '3/4 in', '12 in', '24 in'), cut('Long aprons', 2, '3/4 in', '4 in', '22-1/2 in'), cut('End panels', 2, '3/4 in', '4 in', '10-1/2 in'), cut('Bowl-opening test panel', 1, '1/2 in', '12 in', '12 in')] } },
  { test: /raised dog bed/i, plan: { size: '36 × 24 × 8 in high; fit actual pet', metric: '914 × 610 × 203 mm high', stock: 'straight hardwood frame with washable replaceable sling fabric', joinery: 'braced frame with captured fabric rails and rounded feet', finish: 'fully cured pet-appropriate finish; removable washable fabric', cutList: [cut('Long rails', 2, '1-1/2 in', '3 in', '36 in'), cut('End rails', 2, '1-1/2 in', '3 in', '21 in'), cut('Legs', 4, '1-1/2 in', '1-1/2 in', '8 in'), cut('Sling fabric', 1, 'Fabric', '30 in', '42 in')] } },
  { test: /cat window perch/i, plan: { size: '24 × 12 in platform; supports sized from actual window and load', metric: '610 × 305 mm platform', stock: '3/4 in plywood platform with hardwood edging and rated brackets or straps', joinery: 'platform connected to verified structure with redundant rated support', finish: 'fully cured pet-appropriate finish with removable washable pad', cutList: [cut('Platform', 1, '3/4 in', '12 in', '24 in'), cut('Front edge', 1, '3/4 in', '2 in', '24 in'), cut('Support arms', 2, 'Rated/fit', 'Rated/fit', 'Fit window'), cut('Bracket test block', 1, '1-1/2 in', '4 in', '8 in')] } },
]

function addFeatureParts(plan, title) {
  const parts = [...plan.cutList]
  const names = parts.map((part) => part.part.toLowerCase()).join(' ')
  if (/\bwith (?:one |two |full-extension )?drawers?|\bone drawer|two-drawer/i.test(title) && !/drawer/.test(names)) {
    const count = /two-drawer|two drawers/i.test(title) ? 2 : 1
    parts.push(cut('Drawer sides', count * 2, '1/2 in', '4–6 in', 'Fit measured opening'), cut('Drawer fronts and backs', count * 2, '1/2 in', '4–6 in', 'Opening minus side joinery'), cut('Drawer bottoms', count, '1/4 in', 'Fit groove', 'Fit groove'), cut('Applied drawer fronts', count, '3/4 in', 'Fit reveal', 'Fit reveal'))
  }
  if (/sliding doors/i.test(title) && !/door/.test(names)) parts.push(cut('Sliding doors', 2, '3/4 in', 'Fit opening', 'Fit opening'), cut('Door tracks', 2, 'Per hardware', 'Per hardware', 'Fit opening'))
  if (/shoe shelf/i.test(title) && !/shel(?:f|ves)/.test(names)) parts.push(cut('Shoe shelf', 1, '3/4 in', 'Fit frame depth', 'Fit between legs or case sides'))
  if (/(?:wall-mounted|floating)(?!-look)/i.test(title) && !/cleat|bracket|support|hanger|anchor/.test(names)) parts.push(cut('Wall cleat or rated brackets', 1, 'Per design', 'Fit project', 'Fit project', 'Connect to verified framing or masonry with hardware rated for the complete loaded project'))
  if (/folding|fold-down|drop-leaf|lift-top|adjustable|removable|hidden fasteners|hidden storage/i.test(title) && !/hardware|hinge|adjust/.test(names)) parts.push(cut('Feature-hardware setup blanks', 2, 'Match project', '4 in', '8 in', 'Fit and cycle the exact hardware before machining finished parts'))
  return { ...plan, cutList: parts }
}

export function productionPlanFor(guide) {
  const base = structuredClone(planFor(guide))
  const match = rules.find((rule) => rule.test.test(guide.title))
  return addFeatureParts(match ? { ...base, ...structuredClone(match.plan) } : base, guide.title)
}

export function productionTools(guide, plan) {
  if (guide.id === '003') return [
    { name: 'Combination square', required: true, purpose: 'Lay out square cuts and screw locations' },
    { name: 'Crosscut handsaw', required: true, purpose: 'Cut the five pine parts to length' },
    { name: 'Drill/driver with countersink bit', required: true, purpose: 'Predrill and drive the reinforcing screws' },
  ]
  const title = guide.title
  const cutter = /CNC/i.test(title) ? 'CNC router with verified workholding and simulated toolpath'
    : /lathe|turn/i.test(title) ? 'Lathe with appropriate centers, chuck, and sharp turning tools'
      : /router/i.test(title) ? 'Router with the project-specific bit, guard, and edge support'
        : /table saw/i.test(title) ? 'Table saw with guard, riving knife, and full stock support'
          : /bandsaw/i.test(title) ? 'Bandsaw with an appropriate sharp blade and close-set guides'
            : /hand-tool|bench hook|shooting board|dovetail|mallet/i.test(title) ? 'Sharp handsaw, chisels, and plane suited to the joints'
              : 'Saw suited to the stock, cut, and available support'
  return [
    { name: 'Tape measure, pencil, and verified combination square', required: true, purpose: `Lay out the ${plan.size} baseline from one reference` },
    { name: cutter, required: true, purpose: 'Cut the listed parts while controlling the workpiece and offcut' },
    { name: 'Drill/driver and project-appropriate bits', required: !/one-piece|turning blank/i.test(plan.joinery), purpose: 'Predrill hardware and assemble without splitting stock' },
    { name: 'Clamps, cauls, and workholding sized to the parts', required: true, purpose: 'Prove the dry fit and preserve alignment during assembly' },
    { name: 'Sanding block, scraper, or random-orbit sander with extraction', required: false, purpose: 'Refine surfaces without rounding reference edges' },
  ]
}

export function productionMaterials(plan) {
  return [
    { name: 'Primary stock', quantity: plan.stock, notes: 'Buy enough for the cut list, matching setup pieces, milling allowance, and visible defects' },
    { name: 'Joinery supplies', quantity: 'One complete project set', notes: plan.joinery },
    { name: 'Adhesive and fasteners', quantity: 'Sized to the complete assembly', notes: 'Match the exposure and load; follow current open, clamp, cure, pilot-hole, and embedment guidance' },
    { name: 'Abrasives', quantity: 'The sequence proven on the sample', notes: 'Start with the finest grit that removes the actual defect' },
    { name: 'Finish', quantity: 'One labeled sample plus project coverage', notes: plan.finish },
  ]
}
